name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.6'
          - '3.10'
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: 'pip install -e . -r requirements-dev.txt'
      - run: pytest -vvv --cov .
      - uses: codecov/codecov-action@v2
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - run: 'pip install -e . -r requirements-lint.txt'
      - run: flake8
      - run: mypy --strict laituri
